version: '3'
services:
  api-server:
    build: ./
    entrypoint: [ "npm", "run", "dev" ]
    env_file: ./config/config.env
    ports:
      - '3000:3000'
    networks:
      - goodtinstory-app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=goodtinstory
    ports:
      - 
    networks:
      - goodtinstory-app
    volumes:
      - mongo-data:/data/db

networks:
  goodtinstory-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local
